name: my_flutter_portfolio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.2
  flutter_icons: ^1.1.0
  fancy_shimmer_image: ^1.0.1
  carousel_slider: ^2.0.0
  json_serializable: ^3.3.0
  badges: ^1.1.1
  url_launcher: ^5.4.5
  flutter_spinkit: ^4.1.2+1
  animations: ^1.0.0+5
  animated_card: ^1.0.0+8
  country_icons: ^1.1.1
  expansion_tile_card: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/images/